### ISSUE TITLE
Crie um arquivo reset.css

### ISSUE THREAD

**Issue by allineantunnes** [alinealien/jogo-da-velha#3]
# Crie um arquivo reset.css

### Sugiro que adicione um arquivo de normalização de browsers 'reset.css'

![testeimg](https://github.com/alinealien/jogo-da-velha/assets/156844771/9c8aa198-eb8f-4fca-8b03-6650a28f3d04)

**Comment by alinealien** [comment]
Olá, obrigada pelo seu apontamento. Estarei adicionando o arquivo reset.css
